name: event_planning_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^4.0.4
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0
  image_picker: ^1.1.2
  supabase_flutter: ^2.8.4
  mongo_dart: ^0.10.3
  shared_preferences: ^2.2.3
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  image: ^4.1.3
  path_provider: ^2.1.4
  appwrite: ^12.0.1
  file_picker: ^8.0.5
  http: ^1.4.0
  flutterwave_standard: ^1.1.0
  url_launcher: ^6.3.1
  firebase_messaging: ^15.2.6
  connectivity_plus: ^6.1.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/image/
